### ISSUE TITLE
error: unknown property attribute 'strong'

### ISSUE THREAD

**Issue by microspino** [ChristianKienle/OSXBoilerplate#1]
Unable to compile for 10.6 on Snow Leopard 10.6.8 and XCode 4 Version 4.0.2. I get:

error: unknown property attribute 'strong' for these lines inside OSBAppDelegate.h

@property (readonly, strong, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator;
@property (readonly, strong, nonatomic) NSManagedObjectModel *managedObjectModel;
@property (readonly, strong, nonatomic) NSManagedObjectContext *managedObjectContext;

In the project tree libz.1.2.5.dylib seems also missed.

Wht can I do?

**Comment by ChristianKienle** [comment]
The Boilerplate is for 10.7 (Xcode 4.2). ;)
